// Auto-generated by scripts/extract-facilities.py — do not hand-edit.
window.FACILITY_DATA = {
  "beckmanbb": {
    "title": "beckmanbb",
    "sections": [
      {
        "heading": "Beckman HS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/beckman-hs-bb/baseball",
        "height": "750",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://beckman-hs.ipostsports.net/index.html",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/beckmanhs/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "lahabrabb": {
    "title": "lahabrabb",
    "sections": [
      {
        "heading": "La Habra HS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/lahabra-hs-bb/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://lahabra-hs.ipostsports.net/index.html",
        "height": "500",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/lahabrahs/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "lahsbb-old": {
    "title": "lahsbb-old",
    "sections": [
      {
        "heading": "LAHS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net:9443/los-alamitos-hs-bb/baseball",
        "height": "600",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://lahs-bb.ipostsports.net/index.html",
        "height": "550",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/lahsbb/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "lahssb": {
    "title": "lahssb",
    "sections": [
      {
        "heading": "LAHS Softball Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net:9443/los-alamitos-hs-bb/softball",
        "height": "600",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "Start - Starts a camera stream for public view",
          "Stop - Stops a camera stream from public view",
          "Record - Starts a 3 hour camera recording",
          "Note:\u00a0 Recordings can be initiated even if the camera stream is Stopped.\u00a0 Recordings can be added to the File Manager within 24 hours"
        ],
        "src": "https://lahs-sb.ipostsports.net/index.html",
        "height": "350",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://filer.ipostsports.net/lahssb/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "laybs": {
    "title": "laybs",
    "sections": [
      {
        "heading": "LAYBS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap.ipostsports.net/el-dorado-sports-complex",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts a timed recording.",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://laybs.ipostsports.net/index.html",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://filer.ipostsports.net/laybs/",
        "height": "800",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://laybs-field5.ipostsports.net/index.html",
        "height": "650",
        "scrolling": "yes"
      }
    ]
  },
  "proathletics": {
    "title": "proathletics",
    "sections": [
      {
        "heading": "Pro Athletics Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap.ipostsports.net/pro-athletics",
        "height": "600",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped.",
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://laybs.ipostsports.net:65443/proath/",
        "height": "660",
        "scrolling": "yes"
      }
    ]
  },
  "tustinbb": {
    "title": "tustinbb",
    "sections": [
      {
        "heading": "Tustin HS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/tustin-hs-bb/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream for public view",
          "Stop - Stop the stream from public view",
          "Record Start - Starts a 3-hour\u00a0 recording",
          "Note:\u00a0 You can record even when the camera stream is stopped.",
          "Recordings will stop automatically."
        ],
        "src": "https://tustin-hs.ipostsports.net/index.html",
        "height": "300",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/tustinhs/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "woodbridge": {
    "title": "woodbridge",
    "sections": [
      {
        "heading": "Woodbridge High School",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap.ipostsports.net/",
        "height": "600",
        "scrolling": "yes"
      }
    ]
  },
  "doug": {
    "title": "doug",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net/beckman-hs-bb/baseball",
        "height": "750",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://beckman-hs.ipostsports.net/index.html",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [],
        "src": "https://scheron.ipostsports.net/beckmanhs/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "fvbbvar": {
    "title": "fvbbvar",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net/fvhs/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://fountain-valley-hs.ipostsports.net/index.html",
        "height": "450",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/fvhsbb/",
        "height": "850",
        "scrolling": "yes"
      }
    ]
  },
  "buenaparkbb": {
    "title": "buenaparkbb",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net/buena-park-hs/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://buena-park-hs.ipostsports.net/index.html",
        "height": "500",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/bphsbb/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "sonorabb": {
    "title": "sonorabb",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/sonora-hs/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream",
          "Stop - Stop the stream",
          "Record Start - Starts a recording",
          "Record Stop - Stops a recording",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://sonora-hs.ipostsports.net/index.html",
        "height": "500",
        "scrolling": "no"
      },
      {
        "heading": "File Manager",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://filer.ipostsports.net/sonorahsbb/",
        "height": "850",
        "scrolling": "yes"
      }
    ]
  },
  "laybs-sb": {
    "title": "laybs-sb",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap.ipostsports.net/el-dorado-sports-complex/softball",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts recording for a set time and will stop automatically.",
          "Note:\u00a0 You can record even when the camera stream has been stopped"
        ],
        "src": "https://laybs.ipostsports.net/sb.html",
        "height": "300",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://laybs.ipostsports.net:65443/lahabrahs/",
        "height": "650",
        "scrolling": "yes"
      }
    ]
  },
  "sonorasb": {
    "title": "sonorasb",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/sonora-hs/softball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream for public view",
          "Stop - Stop the stream from public view",
          "Record Start - Starts recording for a set time and will stop automatically.",
          "Note:\u00a0 You can record even when the camera stream has been stopped"
        ],
        "src": "https://sonora-hs.ipostsports.net/sb.html",
        "height": "100",
        "scrolling": "no"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://filer.ipostsports.net/sonorahssb/",
        "height": "850",
        "scrolling": "yes"
      }
    ]
  },
  "unibb": {
    "title": "unibb",
    "sections": [
      {
        "heading": "University HS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/universityhs/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "Start - Start the stream for public view",
          "Stop - Stop the stream from public view",
          "Record Start - Starts a recording for 3 hrs. The recording will automatically stop after 3 hours.",
          "Note:\u00a0 You can record even when the camera stream is stopped from public view."
        ],
        "src": "https://university-hs.ipostsports.net/index.html",
        "height": "450",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/universityhs/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "rover": {
    "title": "rover",
    "sections": [
      {
        "heading": "Rover Admin Windrow",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net:9443/windrow-park-irvine/baseball",
        "height": "500",
        "scrolling": "no"
      },
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://windrow.ipostsports.net/index.html",
        "height": "300",
        "scrolling": "no"
      },
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://scheron.ipostsports.net/windrow-admin/",
        "height": "950",
        "scrolling": "yes"
      }
    ]
  },
  "hsallstar": {
    "title": "hsallstar",
    "sections": [
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://gametap.ipostsports.net:9443/great-park/baseball",
        "height": "650",
        "scrolling": "yes"
      }
    ]
  },
  "fran": {
    "title": "fran",
    "sections": [
      {
        "heading": "Admin for Rover System",
        "paragraphs": [],
        "src": "https://laybs.ipostsports.net:65443/filemgr-fran/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "peter": {
    "title": "peter",
    "sections": [
      {
        "heading": "Admin for Rover System",
        "paragraphs": [],
        "src": "https://laybs.ipostsports.net:65443/filemgr-peter/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "steve": {
    "title": "steve",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net:9443/fountainvalleyhs/baseball",
        "height": "600",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://laybs.ipostsports.net:65443/fountainvalleyhs/",
        "height": "650",
        "scrolling": "yes"
      }
    ]
  },
  "lahsbb": {
    "title": "lahsbb",
    "sections": [
      {
        "heading": "LAHS Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/los-alamitos-hs-bb/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts a timed recording.",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://lahs-bb.ipostsports.net/index.html",
        "height": "550",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://scheron.ipostsports.net/lahsbb/",
        "height": "900",
        "scrolling": "yes"
      }
    ]
  },
  "lamiradasb": {
    "title": "lamiradasb",
    "sections": [
      {
        "heading": "Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/lamiradahs-sb/softball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts a timed recording",
          "Note:\u00a0 You can record even when the camera stream is stopped"
        ],
        "src": "https://lamiradasb.ipostsports.net/index.html",
        "height": "670",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for recordings show up"
        ],
        "src": "https://filer.ipostsports.net/lamiradahssb/",
        "height": "850",
        "scrolling": "yes"
      }
    ]
  },
  "yorbalindabb": {
    "title": "yorbalindabb",
    "sections": [
      {
        "heading": "Camera View Section",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/yorbalinda/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts a timed recording",
          "Note:\u00a0 You can record even when the camera stream is stopped"
        ],
        "src": "https://yorbalindahsbb.ipostsports.net/index.html",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for recordings show up"
        ],
        "src": "https://filer.ipostsports.net/yorbalindahsbb/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "brent": {
    "title": "brent",
    "sections": [
      {
        "heading": "Camera View",
        "paragraphs": [],
        "src": "https://gametap-noback.ipostsports.net:9443/lamiradahssb/softball",
        "height": "600",
        "scrolling": "yes"
      }
    ]
  },
  "nphbb": {
    "title": "nphbb",
    "sections": [
      {
        "heading": "Newport Harbor  Camera View",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/newport-harbor-bb/baseball",
        "height": "650",
        "scrolling": "yes"
      },
      {
        "heading": "Stream Administrator",
        "paragraphs": [
          "START - Start the stream for public view",
          "STOP - Stop the stream from public view",
          "RECORD START - Starts a timed recording.",
          "Note:\u00a0 You can record even when the camera stream is stopped."
        ],
        "src": "https://newport-harbor.ipostsports.net/index.html",
        "height": "450",
        "scrolling": "yes"
      },
      {
        "heading": "File Manager - Recorded Videos",
        "paragraphs": [
          "Recorded streams are viewed here.\u00a0 Allow 24 hours for videos to be processed"
        ],
        "src": "https://filer.ipostsports.net/newportharborbb/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "edhsbb": {
    "title": "edhsbb",
    "sections": [
      {
        "heading": "El Dorado Baseball  Camera View",
        "paragraphs": [
          "Use the buttons to check the streams.",
          "Refresh the view by selecting the Back button and selecting the sport and camera(s)."
        ],
        "src": "https://gametap-noback.ipostsports.net/eldoradohs/baseball",
        "height": "800",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "START - Start stream for public view",
          "STOP - Stop stream from public view",
          "RECORD START - Start recording for 3 hours.",
          "Note:\u00a0 Recordings can be started even when Steams are Stopped."
        ],
        "src": "https://eldorado-hs.ipostsports.net/index.html",
        "height": "400",
        "scrolling": "yes"
      },
      {
        "heading": null,
        "paragraphs": [
          "Allow 24 hours for recordings to be available in the list below."
        ],
        "src": "https://filer.ipostsports.net/eldoradohs/",
        "height": "800",
        "scrolling": "yes"
      }
    ]
  },
  "jimmyv": {
    "title": "jimmyv",
    "sections": [
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://gametap.ipostsports.net",
        "height": "650",
        "scrolling": "yes"
      }
    ]
  },
  "mpkarg25": {
    "title": "mpkarg25",
    "sections": [
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://gametap.ipostsports.net",
        "height": "750",
        "scrolling": "yes"
      }
    ]
  },
  "bsclaw001": {
    "title": "bsclaw001",
    "sections": [
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://gametap.ipostsports.net",
        "height": "750",
        "scrolling": "yes"
      }
    ]
  },
  "vippreview": {
    "title": "vippreview",
    "sections": [
      {
        "heading": null,
        "paragraphs": [],
        "src": "https://gametap.ipostsports.net",
        "height": "750",
        "scrolling": "yes"
      }
    ]
  }
};
