#!/usr/bin/env python3
"""
Regenerates /facility-data.js from the WordPress export XML.

Every WP `page` post that isn't one of the hand-built marketing pages
(facilities, gametap, promo, events, ncs, home) is treated as a facility/
school landing page: a stack of {heading, paragraphs, iframe} blocks.
That data feeds the single /facility.html template at request time, so
adding or updating a facility page never means hand-writing new HTML.

Usage: python3 scripts/extract-facilities.py [path-to-wp-export.xml]
"""
import xml.etree.ElementTree as ET
import re
import sys
import json
import os

DEFAULT_XML = "/Users/michaelmcgrath/Downloads/ipostsports.WordPress.2026-07-06.xml"
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "facility-data.js")

NS = {
    "wp": "http://wordpress.org/export/1.2/",
    "content": "http://purl.org/rss/1.0/modules/content/",
}

SKIP_SLUGS = {"facilities", "gametap", "promo", "events", "ncs", "home", None}

IFRAME_RE = re.compile(r"<iframe([^>]*)>.*?</iframe>", re.IGNORECASE | re.DOTALL)
ATTR_RE = re.compile(r'(\w+)="([^"]*)"')
STYLE_STRIP_RE = re.compile(r"<style>.*?</style>", re.IGNORECASE | re.DOTALL)
H2_RE = re.compile(r"<h2>(.*?)</h2>", re.IGNORECASE | re.DOTALL)
P_RE = re.compile(r"<p>(.*?)</p>", re.IGNORECASE | re.DOTALL)
TAG_STRIP_RE = re.compile(r"<[^>]+>")


def clean(s):
    return TAG_STRIP_RE.sub("", s).strip()


def extract(xml_path):
    tree = ET.parse(xml_path)
    channel = tree.getroot().find("channel")
    pages = {}

    for item in channel.findall("item"):
        ptype = item.find("wp:post_type", NS)
        if ptype is None or ptype.text != "page":
            continue
        status = item.find("wp:status", NS)
        if status is None or status.text != "publish":
            continue
        slug_el = item.find("wp:post_name", NS)
        slug = slug_el.text if slug_el is not None else None
        if slug in SKIP_SLUGS:
            continue

        content_el = item.find("content:encoded", NS)
        content = STYLE_STRIP_RE.sub("", content_el.text or "")

        sections = []
        last_end = 0
        for m in IFRAME_RE.finditer(content):
            preceding = content[last_end:m.start()]
            attrs = dict(ATTR_RE.findall(m.group(1)))
            last_end = m.end()

            heading_match = H2_RE.search(preceding)
            paragraphs = [clean(p) for p in P_RE.findall(preceding)]

            height_raw = attrs.get("height", "600px")
            height_match = re.match(r"(\d+)", height_raw)

            sections.append({
                "heading": clean(heading_match.group(1)) if heading_match else None,
                "paragraphs": [p for p in paragraphs if p],
                "src": attrs.get("src", ""),
                "height": height_match.group(1) if height_match else "600",
                "scrolling": attrs.get("scrolling", "yes"),
            })

        title_el = item.find("title")
        pages[slug] = {
            "title": title_el.text if title_el is not None else slug,
            "sections": sections,
        }

    return pages


def main():
    xml_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XML
    pages = extract(xml_path)

    js = "// Auto-generated by scripts/extract-facilities.py — do not hand-edit.\n"
    js += "window.FACILITY_DATA = " + json.dumps(pages, indent=2) + ";\n"

    with open(OUT_PATH, "w") as f:
        f.write(js)

    print(f"Wrote {len(pages)} facility pages to {OUT_PATH}")
    print(json.dumps(sorted(pages.keys())))


if __name__ == "__main__":
    main()
